/**
 * Image Generation Command - AI-powered image creation
 * Uses free APIs to generate images from text prompts
 */

const axios = require('axios');

module.exports = {
    name: 'imagine',
    aliases: ['genimage', 'draw', 'create'],
    category: 'ai',
    description: 'Generate images from text descriptions using AI',
    usage: '.imagine <description>',
    visibility: 'public',

    async execute(sock, msg, args, extra) {
        try {
            if (args.length === 0) {
                return extra.reply(
                    `🎨 *AI Image Generator*\n\n` +
                    `*Usage:* \`.imagine <description>\`\n\n` +
                    `*Examples:*\n` +
                    `• \`.imagine a sunset over mountains with clouds\`\n` +
                    `• \`.imagine a cute cat wearing a space helmet\`\n` +
                    `• \`.imagine futuristic city at night with neon lights\`\n` +
                    `• \`.imagine oil painting of a garden in spring\`\n\n` +
                    `*Tips:*\n` +
                    `• Be descriptive for better results\n` +
                    `• Mention art style (oil painting, digital art, etc.)\n` +
                    `• Add mood/lighting (sunset, dark, bright)`
                );
            }

            const prompt = args.join(' ');
            await extra.reply(`🎨 Generating image for: "${prompt}"\n⏳ This may take a moment...`);

            // Try multiple free image generation APIs
            let imageUrl = null;

            // Method 1: Pollinations.ai (free, no key)
            try {
                const encodedPrompt = encodeURIComponent(prompt);
                imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=512&height=512&nologo=true`;
                // Verify the image exists
                const response = await axios.head(imageUrl, { timeout: 10000 });
                if (response.status !== 200) imageUrl = null;
            } catch (e) {
                imageUrl = null;
            }

            // Method 2: Stable Diffusion via HuggingFace (free inference)
            if (!imageUrl) {
                try {
                    const res = await axios.post(
                        'https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0',
                        { inputs: prompt },
                        {
                            headers: { 'Content-Type': 'application/json' },
                            timeout: 60000,
                            responseType: 'arraybuffer'
                        }
                    );
                    if (res.data && res.data.length > 1000) {
                        // Save as temp file and send
                        const fs = require('fs');
                        const path = require('path');
                        const tempPath = path.join(__dirname, '../../temp', `gen_${Date.now()}.png`);
                        fs.writeFileSync(tempPath, res.data);

                        await sock.sendMessage(extra.from, {
                            image: fs.readFileSync(tempPath),
                            caption: `🎨 *AI Generated Image*\n\n📝 Prompt: ${prompt}\n\n> Generated by EDBOTS AI`
                        }, { quoted: msg });

                        // Cleanup
                        setTimeout(() => { try { fs.unlinkSync(tempPath); } catch (e) {} }, 30000);
                        return;
                    }
                } catch (e) {
                    console.error('[GENIMAGE] HuggingFace failed:', e.message);
                }
            }

            // Send URL-based image
            if (imageUrl) {
                await sock.sendMessage(extra.from, {
                    image: { url: imageUrl },
                    caption: `🎨 *AI Generated Image*\n\n📝 Prompt: ${prompt}\n\n> Generated by EDBOTS AI`
                }, { quoted: msg });
            } else {
                await extra.reply('❌ Image generation failed. Please try a different prompt or try again later.');
            }

        } catch (error) {
            console.error('[GENIMAGE ERROR]', error);
            await extra.reply('❌ Image generation error.');
        }
    }
};
